config/routes.rb
Rails.application.routes.draw do
  resources :temperates
  resources :rates
  devise_for :users
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :admins do
    get 'view_user', on: :collection
  end

  resources :payments do
    get 'choose_payment', on: :collection
    get 'cancel_payment', on: :collection
  end


  resources :orders do
    get 'admin_orders', on: :collection
    get 'buyer_orders', on: :collection
    get 'full_order', on: :member
  end

  resources :buyers do
    get :add_cart, on: :member
  end

  resources :profiles do
   
  end

  resources :pages do
    get 'home', on: :collection
    get 'check_out', on: :collection
    get :remove_cart_product, on: :member
    get :add_one, on: :member
    get :reduce_one, on: :member
    get 'orderConfirm', on: :collection
  end

  resources :categories

  root to: "pages#home"
end

app/models/temperate.rb
# == Schema Information
#
# Table name: temperates
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Temperate < ApplicationRecord
    
    has_one_attached :temp_transferent
end

app/controllers/temperates_controller.rb
class TemperatesController < ApplicationController
  before_action :set_temperate, only: [:show, :edit, :update, :destroy]

  # GET /temperates
  def index
    @temperates = Temperate.all
  end

  # GET /temperates/1
  def show
  end

  # GET /temperates/new
  def new
    @temperate = Temperate.new
  end

  # GET /temperates/1/edit
  def edit
    if session[:transferent] == 'created'
      @temperate = Temperate.where(user_id: current_user.id).last
    end
  end

  # POST /temperates
  def create
    @temperate = Temperate.new(temperate_params)

    if @temperate.save
      redirect_to @temperate, notice: 'Temperate was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /temperates/1
  def update
    @temperate = Temperate.where(user_id: current_user.id).last
    if @temperate.update(temperate_params)
      redirect_to '/pages/check_out', notice: '截图上传成功'
    else
      render :edit
    end
  end


  # DELETE /temperates/1
  def destroy
    @temperate.destroy
    redirect_to temperates_url, notice: 'Temperate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperate
      @temperate = Temperate.where(user_id: current_user.id).last
    end

    # Only allow a list of trusted parameters through.
    def temperate_params
      # params.fetch(:temperate, :temp_transferent)
      params.require(:temperate).permit(:temp_transferent)
    end

    
end

app/helpers/temperates_helper.rb
module TemperatesHelper
end

app/views/temperates/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@temperate) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    %p.text-white 上传照片：
    = f.file_field :temp_transferent
  %br/
  .form-actions
    = link_to '返回','/payments/cancel_payment', class:'btn btn-primary'
    = f.submit "上传", class:'btn btn-primary'

app/views/temperates/edit.html.haml
%h1.blue-shadow 上传截图

= render 'form'

app/views/temperates/index.html.haml
%h1 Listing temperates

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @temperates.each do |temperate|
      %tr
        %td= link_to 'Show', temperate
        %td= link_to 'Edit', edit_temperate_path(temperate)
        %td= link_to 'Destroy', temperate, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Temperate', new_temperate_path

app/views/temperates/new.html.haml
%h1 New temperate

= render 'form'

= link_to 'Back', temperates_path

app/views/temperates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_temperate_path(@temperate)
\|
= link_to 'Back', temperates_path