config/routes.rb
Rails.application.routes.draw do
  resources :temperates
  resources :rates
  devise_for :users
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :admins do
    get 'view_user', on: :collection
  end

  resources :payments do
    get 'choose_payment', on: :collection
    get 'cancel_payment', on: :collection
  end


  resources :orders do
    get 'admin_orders', on: :collection
    get 'buyer_orders', on: :collection
    get 'full_order', on: :member
  end

  resources :buyers do
    get :add_cart, on: :member
  end

  resources :profiles do
   
  end

  resources :pages do
    get 'home', on: :collection
    get 'check_out', on: :collection
    get :remove_cart_product, on: :member
    get :add_one, on: :member
    get :reduce_one, on: :member
    get 'orderConfirm', on: :collection
  end

  resources :categories

  root to: "pages#home"
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Payment < ApplicationRecord
    has_one_attached :proof
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  def index
    @rate = Rate.first
    @payments = Payment.all
  end

  # GET /payments/1
  def show
    @cart = current_user.cart
    @rate = Rate.first.exchange_rate
    @rmb = (@cart.total_price * @rate).round(2)
    if session[:role] == 'User'
      @temperate = Temperate.create(user_id: current_user.id)
      session[:transferent] = 'created'
      @total = @cart.total_price
    end

  end

  def choose_payment
    @payments = Payment.all
  end

  def cancel_payment
    # @cart = current_user.cart
    if session[:transferent] = 'created'
      @order_to_cencel = Temperate.where(user_id: current_user.id).last
      @order_to_cencel.destroy
      session[:transferent] = 'nil'
    end
      redirect_to '/payments/choose_payment'
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      redirect_to payments_path, notice: '支付方式添加成功'
    else
      render :new
    end
  end

  # PATCH/PUT /payments/1
  def update
    if @payment.update(payment_params)
      redirect_to payments_path, notice: '支付方式更新成功'
    else
      render :edit
    end
  end

  # DELETE /payments/1
  def destroy
    @payment.destroy
    redirect_to payments_url, notice: '支付方式删除成功'
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:name, :proof)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@payment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.file_field :proof,:label_html => { :class => "text-white" }
    = f.input :name, label: '支付方式名称',  :label_html => { :class => "text-white" }
  
  %br/
  .form-actions
    = link_to '返回', payments_path, class:'btn btn-primary'
    = f.submit "提交", class:'btn btn-primary'

app/views/payments/choose_payment.html.haml
.card.align-items-center.mt-5.m-3.pb-5
    %h1.pt-3 请选择您想要支付的方式
    %br/
    .btn-block
        - @payments.each do |payment|
            = link_to "#{payment.name}", payment, class:'btn btn-primary'

app/views/payments/edit.html.haml
.d-flex.justify-content-center
    %h1.mt-5.blue-shadow 修改支付方式

= render 'form'

app/views/payments/index.html.haml
.d-flex.justify-content-center.mt-5.mb-3
    %h1.blue-shadow 管理支付方式
%br/
%p.text-white.fst-italic 当前汇率： #{@rate.exchange_rate}
.row
    - @payments.each do |payment|
        .col-6.col-md-4
            =link_to payment,class: "text-decoration-none" do
                .card.bg-light.h-100
                    .card-img-top
                        -if payment.proof.attached?
                            = image_tag payment.proof, class:'img-fluid'
                        -else 
                            %p 没有图片
                    .card-body
                        %h4.text-black #{payment.name}
                    .card-footer
                        = link_to '编辑', edit_payment_path(payment)
                        = link_to '删除', payment, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
= link_to '添加新支付方式', new_payment_path, class:'btn btn-primary'
= link_to '修改汇率', '/rates/1/edit', class:'btn btn-primary'

app/views/payments/new.html.haml
%h1 New payment

= render 'form'

app/views/payments/show.html.haml
-if session[:role] == 'Admin'
  %br/
  .d-flex.justify-content-center
    %h3 #{@payment.name}
  .d-flex.justify-content-center  
    %p= image_tag @payment.proof, class:'img-fluid'
  = link_to '返回', payments_path, class:'btn btn-primary'
  = link_to '编辑', edit_payment_path(@payment), class:'btn btn-primary'

-if session[:role] == 'User'
  %br/
  .d-flex.justify-content-center
    %h1.blue-shadow #{@payment.name}
  .d-flex.justify-content-center  
    %p= image_tag @payment.proof, class:'img-fluid'
  .d-flex.justify-content-center
    %h4.text-white 请支付(£): #{@total.round(2)} 或者 (¥): #{@rmb}
 
  %br/
  = link_to '取消支付', '/payments/cancel_payment', class:'btn btn-primary'
  = link_to '上传支付截图', "/temperates/#{@temperate.id}/edit", class:'btn btn-primary'
  