config/routes.rb
Rails.application.routes.draw do
  resources :temperates
  resources :rates
  devise_for :users
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :admins do
    get 'view_user', on: :collection
  end

  resources :payments do
    get 'choose_payment', on: :collection
    get 'cancel_payment', on: :collection
  end


  resources :orders do
    get 'admin_orders', on: :collection
    get 'buyer_orders', on: :collection
    get 'full_order', on: :member
  end

  resources :buyers do
    get :add_cart, on: :member
  end

  resources :profiles do
   
  end

  resources :pages do
    get 'home', on: :collection
    get 'check_out', on: :collection
    get :remove_cart_product, on: :member
    get :add_one, on: :member
    get :reduce_one, on: :member
    get 'orderConfirm', on: :collection
  end

  resources :categories

  root to: "pages#home"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#
class Product < ApplicationRecord
    has_many_attached :images
    belongs_to :category

    has_many :cart_products, dependent: :destroy
    has_many :carts, through: :cart_products

    has_many :order_products, dependent: :destroy
    has_many :order, through: :cart_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @cocktail = Product.where(category_id:"1")
    @whisky = Product.where(category_id:"2")
  end



  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def create_cart
    @cart = current_user.create_cart
    redirect_to "/"
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def getProduct(order_products)
        goods = ''
        order_products.each do |order_product|
            goods =  goods +  ' ' + (Product.find(order_product.product_id).name + 'X' + order_product.quantity.to_s)
        end
        return goods
    end


end

app/views/products/_form.html.haml
= simple_form_for(@product) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    %p 上传照片：
    = f.file_field :images, multiple: true
    = f.input :name, label: '名称'
    = f.input :description, label: '描述'
    = f.input :price, label: '价格'
    = f.association :category, label: '类别'
  %br/
  .form-actions
    = f.button :submit, class:'btn btn-primary'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
.d-flex.justify-content-center.mt-5.mb-4
  %h1.blue-shadow 产品管理

= link_to '添加新产品', new_product_path,class:'btn btn-primary'
= link_to '添加新类别', new_category_path,class:'btn btn-primary'

%br/
%br/
%h1.text-white Cocktail:
.row
  - @cocktail.each do |cocktail|
    .col-6.col-md-3.mb-2
      .card.h-100
        .card-img-top.p-2
          = image_tag cocktail.images[0], class:'img-fluid'
        .card-body
          %p.fw-bold #{cocktail.name}
          %p 描述:  #{cocktail.description}
          %p 价格(£):  #{cocktail.price}
          -# = link_to '查看', cocktail
          = link_to '编辑', edit_product_path(cocktail)
          = link_to '删除', cocktail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br/

%h1.text-white Whisky:
.row
  - @whisky.each do |whisky|
    .col-6.col-md-3.mb-2
      .card.h-100
        .card-img-top.p-2
          = image_tag whisky.images[0], class:'img-fluid'
        .card-body
          %p.fw-bold #{whisky.name}
          %p 描述:  #{whisky.description}
          %p 价格(£):  #{whisky.price}
          -# = link_to 'Show', whisky
          = link_to '编辑', edit_product_path(whisky)
          = link_to '删除', whisky, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Price:
  = @product.price

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path