config/routes.rb
Rails.application.routes.draw do
  resources :temperates
  resources :rates
  devise_for :users
  resources :users
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :admins do
    get 'view_user', on: :collection
  end

  resources :payments do
    get 'choose_payment', on: :collection
    get 'cancel_payment', on: :collection
  end


  resources :orders do
    get 'admin_orders', on: :collection
    get 'buyer_orders', on: :collection
    get 'full_order', on: :member
  end

  resources :buyers do
    get :add_cart, on: :member
  end

  resources :profiles do
   
  end

  resources :pages do
    get 'home', on: :collection
    get 'check_out', on: :collection
    get :remove_cart_product, on: :member
    get :add_one, on: :member
    get :reduce_one, on: :member
    get 'orderConfirm', on: :collection
  end

  resources :categories

  root to: "pages#home"
end

app/models/rate.rb
# == Schema Information
#
# Table name: rates
#
#  id            :bigint           not null, primary key
#  exchange_rate :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Rate < ApplicationRecord
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  def create
    @rate = Rate.new(rate_params)

    if @rate.save
      redirect_to payments_path, notice: 'Rate was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rates/1
  def update
    if @rate.update(rate_params)
      redirect_to payments_path, notice: '汇率修改成功'
    else
      render :edit
    end
  end

  # DELETE /rates/1
  def destroy
    @rate.destroy
    redirect_to payments_path, notice: 'Rate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:exchange_rate)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@rate) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :exchange_rate

  .form-actions
    = link_to '返回', rates_path
    = f.submit "提交"

app/views/rates/edit.html.haml
%h1 Editing rate

= render 'form'

app/views/rates/index.html.haml
%h1 Listing rates

%table
  %thead
    %tr
      %th Exchange rate
      %th
      %th
      %th

  %tbody
    - @rates.each do |rate|
      %tr
        %td= rate.exchange_rate
        %td= link_to 'Show', rate
        %td= link_to 'Edit', edit_rate_path(rate)
        %td= link_to 'Destroy', rate, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rate', new_rate_path

app/views/rates/new.html.haml
%h1 New rate

= render 'form'

= link_to 'Back', rates_path

app/views/rates/show.html.haml
%p#notice= notice

%p
  %b Exchange rate:
  = @rate.exchange_rate

= link_to 'Edit', edit_rate_path(@rate)
\|
= link_to 'Back', rates_path